#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: bellman-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: bellman
#  template:
#    metadata:
#      labels:
#        app: bellman
#    spec:
#      containers:
#        - name: bellman-container
#          image: aryanpatel111/bellman-shortest-path-finder
#          ports:
#            - containerPort: 3001  # Assuming your Spring Boot app listens on port 8080



apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: aryanpatel111/bellman-shortest-path-finder
          ports:
            - containerPort: 9191
          resources:
            requests:
              cpu: "100m"  # Request 100 milliCPU (0.1 CPU)
              memory: "512Mi"  # Minimum request of 512 Mebibytes of memory
            limits:
              cpu: "200m"  # Limit to 200 milliCPU (0.2 CPU)
              memory: "1Gi"
